# Generated by Django 6.0.3 on 2026-03-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='recived_at',
            new_name='received_at',
        ),
    ]
