# Generated by Django 6.0.3 on 2026-03-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal Project'), ('experience', 'Work Experience')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
